name: Build and Release Bazel Target

on:
  push:
    tags:
      - '*'

permissions:
  contents: write  # Ensure the token has write permission for contents

jobs:
  build-osx-arm64:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Bazel output
      uses: actions/cache@v2
      id: cache-bazel
      with:
        path: |
          ~/.cache/bazel
          bazel-out
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Create artifact directory
      run: mkdir -p osx-artifacts-arm64

    - name: Build for arm64
      run: |
        wget -q https://github.com/bazelbuild/bazel/releases/download/7.3.1rc2/bazel-7.3.1rc2-darwin-arm64
        mv bazel-7.3.1rc2-darwin-arm64 bazel-arm64
        chmod +x bazel-arm64
        ./bazel-arm64 info
        ./bazel-arm64 build -c opt --host_cpu=darwin_arm64 //xls/public:libxls.dylib //xls/dslx:interpreter_main //xls/dslx/lsp:dslx_ls //xls/tools:opt_main //xls/tools:codegen_main //xls/dslx/ir_convert:ir_converter_main

    - name: Verify arm64 binaries
      run: |
        lipo -info bazel-bin/xls/public/libxls.dylib

    - name: Collect arm64 artifacts
      run: |
        cp bazel-bin/xls/public/libxls.dylib osx-artifacts-arm64/libxls-arm64.dylib
        cp bazel-bin/xls/dslx/interpreter_main osx-artifacts-arm64/dslx_interpreter_main-arm64
        cp bazel-bin/xls/dslx/lsp/dslx_ls osx-artifacts-arm64/dslx_ls-arm64
        cp bazel-bin/xls/tools/opt_main osx-artifacts-arm64/opt_main-arm64
        cp bazel-bin/xls/tools/codegen_main osx-artifacts-arm64/codegen_main-arm64
        cp bazel-bin/xls/dslx/ir_convert/ir_converter_main osx-artifacts-arm64/ir_converter_main-arm64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: osx-artifacts-arm64
        path: osx-artifacts-arm64/

  build-osx-x64:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Bazel output
      uses: actions/cache@v2
      id: cache-bazel
      with:
        path: |
          ~/.cache/bazel
          bazel-out
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Create artifact directory
      run: mkdir -p osx-artifacts-x64

    - name: Build for x86_64
      run: |
        wget -q https://github.com/bazelbuild/bazel/releases/download/7.3.1rc2/bazel-7.3.1rc2-darwin-x86_64
        mv bazel-7.3.1rc2-darwin-x86_64 bazel-x86_64
        chmod +x bazel-x86_64
        ./bazel-x86_64 info
        ./bazel-x86_64 build -c opt //xls/public:libxls.dylib //xls/dslx:interpreter_main //xls/dslx/lsp:dslx_ls //xls/tools:opt_main //xls/tools:codegen_main //xls/dslx/ir_convert:ir_converter_main

    - name: Verify x86_64 binaries
      run: |
        lipo -info bazel-bin/xls/public/libxls.dylib

    - name: Collect x86_64 artifacts
      run: |
        cp bazel-bin/xls/public/libxls.dylib osx-artifacts-x64/libxls-x64.dylib
        cp bazel-bin/xls/dslx/interpreter_main osx-artifacts-x64/dslx_interpreter_main-x64
        cp bazel-bin/xls/dslx/lsp/dslx_ls osx-artifacts-x64/dslx_ls-x64
        cp bazel-bin/xls/tools/opt_main osx-artifacts-x64/opt_main-x64
        cp bazel-bin/xls/tools/codegen_main osx-artifacts-x64/codegen_main-x64
        cp bazel-bin/xls/dslx/ir_convert/ir_converter_main osx-artifacts-x64/ir_converter_main-x64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: osx-artifacts-x64
        path: osx-artifacts-x64/

  build-rocky8:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner
    container: rockylinux:8 # Specify the Docker container
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Bazel output
      uses: actions/cache@v2
      id: cache-bazel
      with:
        path: |
          ~/.cache/bazel
          bazel-out
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Install bazelisk
      run: |
        dnf install -y curl unzip
        curl -Lo bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64
        chmod +x bazelisk
        mv bazelisk /usr/local/bin/
        bazelisk version

    - name: Install Clang-17
      run: |
        dnf install -y llvm-toolset

    - name: Note Clang version
      run: clang-17 --version

    - name: Install build essentials
      run: |
        dnf groupinstall -y "Development Tools"
        dnf install -y libstdc++-devel
        dnf install -y python3

    - name: Build Bazel target
      run: |
        CC=clang-17 CXX=clang++-17 bazelisk build -c opt //xls/public:libxls.so //xls/public:c_api //xls/dslx:interpreter_main //xls/dslx/lsp:dslx_ls //xls/tools:opt_main //xls/tools:codegen_main //xls/dslx/ir_convert:ir_converter_main

    - name: Create artifact directory
      run: mkdir -p rocky8-artifacts

    - name: Copy Bazel target to rocky8-artifacts
      run: |
        cp bazel-bin/xls/public/libxls.so rocky8-artifacts/libxls-rocky8.so
        cp bazel-bin/xls/dslx/interpreter_main rocky8-artifacts/dslx_interpreter_main-rocky8
        cp bazel-bin/xls/dslx/lsp/dslx_ls rocky8-artifacts/dslx_ls-rocky8
        cp bazel-bin/xls/tools/opt_main rocky8-artifacts/opt_main-rocky8
        cp bazel-bin/xls/tools/codegen_main rocky8-artifacts/codegen_main-rocky8
        cp bazel-bin/xls/dslx/ir_convert/ir_converter_main rocky8-artifacts/ir_converter_main-rocky8

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rocky8-artifacts
        path: rocky8-artifacts/

  build-ubuntu2004:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Bazel output
      uses: actions/cache@v2
      id: cache-bazel
      with:
        path: |
          ~/.cache/bazel
          bazel-out
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Install Clang-17
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        sudo apt-get install -y clang-17

    - name: Note Clang version
      run: clang-17 --version

    - name: Build Bazel target
      run: |
        CC=clang-17 CXX=clang++-17 bazelisk build -c opt //xls/public:libxls.so //xls/public:c_api //xls/dslx:interpreter_main //xls/dslx/lsp:dslx_ls //xls/tools:opt_main //xls/tools:codegen_main //xls/dslx/ir_convert:ir_converter_main

    - name: Create artifact directory
      run: mkdir -p ubuntu2004-artifacts

    - name: Copy Bazel target to ubuntu2004-artifacts
      run: |
        cp bazel-bin/xls/public/libxls.so                  ubuntu2004-artifacts/libxls-ubuntu2004.so
        cp bazel-bin/xls/dslx/interpreter_main             ubuntu2004-artifacts/dslx_interpreter_main-ubuntu2004
        cp bazel-bin/xls/dslx/lsp/dslx_ls                  ubuntu2004-artifacts/dslx_ls-ubuntu2004
        cp bazel-bin/xls/tools/opt_main                    ubuntu2004-artifacts/opt_main-ubuntu2004
        cp bazel-bin/xls/tools/codegen_main                ubuntu2004-artifacts/codegen_main-ubuntu2004
        cp bazel-bin/xls/dslx/ir_convert/ir_converter_main ubuntu2004-artifacts/ir_converter_main-ubuntu2004

    - name: Tarball stdlib files to ubuntu2004-artifacts
      run: tar -czvvf ubuntu2004-artifacts/dslx_stdlib.tar.gz xls/dslx/stdlib/*.x

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu2004-artifacts
        path: ubuntu2004-artifacts/


  build-ubuntu2204:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Bazel output
      uses: actions/cache@v2
      id: cache-bazel
      with:
        path: |
          ~/.cache/bazel
          bazel-out
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD') }}
        restore-keys: |
          ${{ runner.os }}-bazel-


    - name: Install Clang-17
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 17
        sudo apt-get install -y clang-17

    - name: Note Clang version
      run: clang-17 --version

    - name: Build Bazel target
      run: |
        CC=clang-17 CXX=clang++-17 bazelisk build -c opt //xls/public:libxls.so //xls/public:c_api //xls/dslx:interpreter_main //xls/dslx/lsp:dslx_ls //xls/tools:opt_main //xls/tools:codegen_main //xls/dslx/ir_convert:ir_converter_main

    - name: Create artifact directory
      run: mkdir -p ubuntu2204-artifacts

    - name: Copy Bazel target to ubuntu2204-artifacts
      run: |
        cp bazel-bin/xls/public/libxls.so                  ubuntu2204-artifacts/libxls-ubuntu2204.so
        cp bazel-bin/xls/dslx/interpreter_main             ubuntu2204-artifacts/dslx_interpreter_main-ubuntu2204
        cp bazel-bin/xls/dslx/lsp/dslx_ls                  ubuntu2204-artifacts/dslx_ls-ubuntu2204
        cp bazel-bin/xls/tools/opt_main                    ubuntu2204-artifacts/opt_main-ubuntu2204
        cp bazel-bin/xls/tools/codegen_main                ubuntu2204-artifacts/codegen_main-ubuntu2204
        cp bazel-bin/xls/dslx/ir_convert/ir_converter_main ubuntu2204-artifacts/ir_converter_main-ubuntu2204

    - name: Tarball stdlib files to ubuntu2204-artifacts
      run: tar -czvvf ubuntu2204-artifacts/dslx_stdlib.tar.gz xls/dslx/stdlib/*.x

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu2204-artifacts
        path: ubuntu2204-artifacts/

  release:
    needs:
      - build-osx-arm64
      - build-osx-x64
      - build-ubuntu2004
      - build-ubuntu2204
      - build-rocky8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download osx-artifacts-arm64
      uses: actions/download-artifact@v2
      with:
        name: osx-artifacts-arm64
        path: osx-artifacts-arm64

    - name: Download osx-artifacts-x64
      uses: actions/download-artifact@v2
      with:
        name: osx-artifacts-x64
        path: osx-artifacts-x64

    - name: Download ubuntu2004-artifacts
      uses: actions/download-artifact@v2
      with:
        name: ubuntu2004-artifacts
        path: ubuntu2004-artifacts

    - name: Download ubuntu2204-artifacts
      uses: actions/download-artifact@v2
      with:
        name: ubuntu2204-artifacts
        path: ubuntu2204-artifacts

    - name: Download rocky8-artifacts
      uses: actions/download-artifact@v2
      with:
        name: rocky8-artifacts
        path: rocky8-artifacts

    - name: Extract tag name
      id: extract_tag
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "Extracted tag name: $TAG_NAME"

    - name: Download GitHub CLI
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.30.0/gh_2.30.0_linux_amd64.tar.gz -o ghcli.tar.gz
        tar -xzf ghcli.tar.gz
        sudo mv gh_2.30.0_linux_amd64/bin/gh /usr/local/bin/

    - name: Create GitHub release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ env.TAG_NAME }}
      run: |
        export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        gh release create "$TAG_NAME" \
          osx-artifacts-arm64/libxls-arm64.dylib          \
          osx-artifacts-arm64/dslx_interpreter_main-arm64 \
          osx-artifacts-arm64/dslx_ls-arm64               \
          osx-artifacts-arm64/opt_main-arm64              \
          osx-artifacts-arm64/codegen_main-arm64          \
          osx-artifacts-arm64/ir_converter_main-arm64     \
          \
          osx-artifacts-x64/libxls-x64.dylib              \
          osx-artifacts-x64/dslx_interpreter_main-x64     \
          osx-artifacts-x64/dslx_ls-x64                   \
          osx-artifacts-x64/opt_main-x64                  \
          osx-artifacts-x64/codegen_main-x64              \
          osx-artifacts-x64/ir_converter_main-x64         \
          \
          ubuntu2004-artifacts/dslx_stdlib.tar.gz                 \
          ubuntu2004-artifacts/libxls-ubuntu2004.so               \
          ubuntu2004-artifacts/dslx_interpreter_main-ubuntu2004   \
          ubuntu2004-artifacts/dslx_ls-ubuntu2004                 \
          ubuntu2004-artifacts/opt_main-ubuntu2004                \
          ubuntu2004-artifacts/codegen_main-ubuntu2004            \
          ubuntu2004-artifacts/ir_converter_main-ubuntu2004       \
          \
          ubuntu2204-artifacts/libxls-ubuntu2204.so               \
          ubuntu2204-artifacts/dslx_interpreter_main-ubuntu2204   \
          ubuntu2204-artifacts/dslx_ls-ubuntu2204                 \
          ubuntu2204-artifacts/opt_main-ubuntu2204                \
          ubuntu2204-artifacts/codegen_main-ubuntu2204            \
          ubuntu2204-artifacts/ir_converter_main-ubuntu2204       \
          \
          rocky8-artifacts/libxls-rocky8.so             \
          rocky8-artifacts/dslx_interpreter_main-rocky8 \
          rocky8-artifacts/dslx_ls-rocky8               \
          rocky8-artifacts/opt_main-rocky8              \
          rocky8-artifacts/codegen_main-rocky8          \
          rocky8-artifacts/ir_converter_main-rocky8     \
          \
          --title "Release $TAG_NAME" \
          --notes "Automated release of $TAG_NAME"
